export const carrierFields = [
  {
    title: "Datos Personales",
    fields: [
      { key: "fullName", label: "Nombre Completo" },
      { key: "socialName", label: "Nombre Social" },
      { key: "nationality", label: "Nacionalidad" },
      { key: "maritalStatus", label: "Estado Civil" },
      { key: "typeCurrent", label: "Tipo de portador" },
      { key: "gender", label: "Género" },
      { key: "run", label: "RUN" },
      { key: "phone", label: "Teléfono" },
      { key: "birthDate", label: "Fecha de Nacimiento" },
    ],
  },
  {
    title: "Causa",
    fields: [
      { key: "penaltyType", label: "Tipo de Pena" },
      { key: "appealsCourt", label: "Corte de Apelaciones" },
      { key: "courtRegion", label: "Región Judicial" },
      { key: "court", label: "Tribunal" },
      { key: "ruc", label: "RUC" },
      { key: "rit", label: "RIT" },
      { key: "rol", label: "ROL" },
    ],
  },
  {
    title: "Monitoreo",
    fields: [
      { key: "crs", label: "CRS" },
      { key: "inclusionExclusionAreas", label: "Áreas de Inclusión/Exclusión" },
      { key: "measureDuration", label: "Duración de la Medida" },
      { key: "controlSchedule", label: "Horario de Control" },
      { key: "effectiveControlPeriod", label: "Periodo de Control Efectivo" },
      { key: "feasibilityRequests", label: "Solicitudes de Factibilidad" },
      { key: "sentence", label: "Sentencia" },
      { key: "installationProgramming", label: "Programación de Instalación" },
      { key: "installationsPerformed", label: "Instalaciones Realizadas" },
      { key: "modificationResolutions", label: "Resoluciones de Modificación" },
      { key: "technicalSupports", label: "Soportes Técnicos" },
      { key: "nonComplianceReports", label: "Informes de Incumplimiento" },
      { key: "controlDays", label: "Días de Control" },
      { key: "uninstallations", label: "Desinstalaciones" },
    ],
  },
];
