export const users = [
  {
    id: 1,
    name: "Yosip Mike Colin",
    nit: "83749234",
    perfil: "Requiriente",
    status: "Activo",
    email: "yosipmikecolin@example.com",
    creation_date: "2022-03-15",
    phone: "+57 310 123 4567",
  },
  {
    id: 2,
    name: "Andres Alfonso",
    nit: "5937450378",
    perfil: "Coordinador",
    status: "Inactivo",
    email: "andresalfonso@example.com",
    creation_date: "2021-07-22",
    phone: "+57 320 234 5678",
  },
  {
    id: 3,
    name: "Maria Salazar",
    nit: "5905645028",
    perfil: "Administrador",
    status: "Activo",
    email: "mariasalazar@example.com",
    creation_date: "2023-01-10",
    phone: "+57 300 345 6789",
  },
  {
    id: 4,
    name: "Luciana Gómez",
    nit: "4538294850",
    perfil: "Requiriente",
    status: "Activo",
    email: "lucianagomez@example.com",
    creation_date: "2022-11-05",
    phone: "+57 315 456 7890",
  },
  {
    id: 5,
    name: "Carlos Pérez",
    nit: "5893247324",
    perfil: "Administrador",
    status: "Inactivo",
    email: "carlosperez@example.com",
    creation_date: "2021-09-30",
    phone: "+57 318 567 8901",
  },
  {
    id: 6,
    name: "Laura Martínez",
    nit: "4823952345",
    perfil: "Requiriente",
    status: "Activo",
    email: "lauramartinez@example.com",
    creation_date: "2023-04-12",
    phone: "+57 311 678 9012",
  },
  {
    id: 7,
    name: "Jorge Fernández",
    nit: "7583940238",
    perfil: "Coordinador",
    status: "Activo",
    email: "jorgefernandez@example.com",
    creation_date: "2022-08-19",
    phone: "+57 313 789 0123",
  },
  {
    id: 8,
    name: "Andrea Torres",
    nit: "9384752384",
    perfil: "Administrador",
    status: "Activo",
    email: "andreatorres@example.com",
    creation_date: "2021-12-25",
    phone: "+57 314 890 1234",
  },
  {
    id: 9,
    name: "Camila Ruiz",
    nit: "8364928472",
    perfil: "Coordinador",
    status: "Inactivo",
    email: "camilaruiz@example.com",
    creation_date: "2023-02-14",
    phone: "+57 317 901 2345",
  },
  {
    id: 10,
    name: "Felipe Mejía",
    nit: "2394853205",
    perfil: "Coordinador",
    status: "Activo",
    email: "felipemejia@example.com",
    creation_date: "2022-05-20",
    phone: "+57 319 012 3456",
  },
  {
    id: 11,
    name: "Paola Herrera",
    nit: "7382947583",
    perfil: "Requiriente",
    status: "Activo",
    email: "paolaherrera@example.com",
    creation_date: "2021-10-08",
    phone: "+57 312 123 4567",
  },
  {
    id: 12,
    name: "Sebastián Vega",
    nit: "5932840239",
    perfil: "Requiriente",
    status: "Inactivo",
    email: "sebastianvega@example.com",
    creation_date: "2023-03-01",
    phone: "+57 316 234 5678",
  },
  {
    id: 13,
    name: "Natalia Castro",
    nit: "8402938472",
    perfil: "Administrador",
    status: "Activo",
    email: "nataliacastro@example.com",
    creation_date: "2022-06-18",
    phone: "+57 310 345 6789",
  },
  {
    id: 14,
    name: "Fernando Morales",
    nit: "7562937482",
    perfil: "Coordinador",
    status: "Inactivo",
    email: "fernandomorales@example.com",
    creation_date: "2021-11-11",
    phone: "+57 320 456 7890",
  },
  {
    id: 15,
    name: "Sofia Rojas",
    nit: "2938745029",
    perfil: "Requiriente",
    status: "Activo",
    email: "sofiarojas@example.com",
    creation_date: "2023-05-09",
    phone: "+57 300 567 8901",
  },
];
export const carriers = [
  {
    id: 1,
    fullName: "Juan Pérez",
    socialName: "Juancho",
    nationality: "Colombia",
    countryCode: "CO",
    maritalStatus: "Soltero",
    gender: "Masculino",
    run: "12345678-9",
    phone: "+57 300 123 4567",
  },
  {
    id: 2,
    fullName: "María García",
    socialName: "Maru",
    nationality: "México",
    countryCode: "MX",
    maritalStatus: "Casada",
    gender: "Femenino",
    run: "87654321-0",
    phone: "+52 55 9876 5432",
  },
  {
    id: 3,
    fullName: "Carlos López",
    socialName: "Carlitos",
    nationality: "Chile",
    countryCode: "CL",
    maritalStatus: "Divorciado",
    gender: "Masculino",
    run: "11223344-5",
    phone: "+56 9 8765 4321",
  },
  {
    id: 4,
    fullName: "Sofía Ramírez",
    socialName: "Sofi",
    nationality: "Argentina",
    countryCode: "AR",
    maritalStatus: "Soltera",
    gender: "Femenino",
    run: "99887766-3",
    phone: "+54 11 1234 5678",
  },
  {
    id: 5,
    fullName: "Andrés González",
    socialName: "Andy",
    nationality: "España",
    countryCode: "ES",
    maritalStatus: "Casado",
    gender: "Masculino",
    run: "33445566-T",
    phone: "+34 600 123 456",
  },
  {
    id: 6,
    fullName: "Lucía Fernández",
    socialName: "Lucy",
    nationality: "Perú",
    countryCode: "PE",
    maritalStatus: "Viuda",
    gender: "Femenino",
    run: "66778899-2",
    phone: "+51 1 6543 2109",
  },
  {
    id: 7,
    fullName: "Miguel Torres",
    socialName: "Mike",
    nationality: "Venezuela",
    countryCode: "VE",
    maritalStatus: "Separado",
    gender: "Masculino",
    run: "11225588-6",
    phone: "+58 212 123 4567",
  },
  {
    id: 8,
    fullName: "Ana Martínez",
    socialName: "Anita",
    nationality: "Uruguay",
    countryCode: "UY",
    maritalStatus: "Soltera",
    gender: "Femenino",
    run: "55443322-1",
    phone: "+598 99 987 654",
  },
  {
    id: 9,
    fullName: "José Díaz",
    socialName: "Pepe",
    nationality: "Paraguay",
    countryCode: "PY",
    maritalStatus: "Soltero",
    gender: "Masculino",
    run: "22334455-7",
    phone: "+595 21 123 456",
  },
  {
    id: 10,
    fullName: "Paula Rodríguez",
    socialName: "Pau",
    nationality: "Bolivia",
    countryCode: "BO",
    maritalStatus: "Casada",
    gender: "Femenino",
    run: "77889966-4",
    phone: "+591 3 456 789",
  },
  {
    id: 11,
    fullName: "Alberto Vargas",
    socialName: "Beto",
    nationality: "Ecuador",
    countryCode: "EC",
    maritalStatus: "Divorciado",
    gender: "Masculino",
    run: "55667788-9",
    phone: "+593 4 678 901",
  },
  {
    id: 12,
    fullName: "Carolina Méndez",
    socialName: "Caro",
    nationality: "Brasil",
    countryCode: "BR",
    maritalStatus: "Soltera",
    gender: "Femenino",
    run: "33221144-8",
    phone: "+55 11 98765-4321",
  },
  {
    id: 13,
    fullName: "Diego Jiménez",
    socialName: "Jimmy",
    nationality: "Panamá",
    countryCode: "PA",
    maritalStatus: "Soltero",
    gender: "Masculino",
    run: "66778899-0",
    phone: "+507 678 9012",
  },
  {
    id: 14,
    fullName: "Gabriela Morales",
    socialName: "Gaby",
    nationality: "Puerto Rico",
    countryCode: "PR",
    maritalStatus: "Viuda",
    gender: "Femenino",
    run: "44556677-1",
    phone: "+1 787 654 3210",
  },
  {
    id: 15,
    fullName: "Ricardo Peña",
    socialName: "Richie",
    nationality: "Honduras",
    countryCode: "HN",
    maritalStatus: "Casado",
    gender: "Masculino",
    run: "11447788-5",
    phone: "+504 2234 5678",
  },
];

export const requesters = [
  {
    fullName: "José Alfredo",
    email: "jose.alfredo@gmail.com",
    phone: "3001234567",
    userType: "Abogado",
    institution: "Tribunal Superior",
    identificationNumber: "AB1234567",
    region: "Bogotá",
    address: "Calle 123 #45-67",
    accessAreas: "Legal",
    registrationDate: "2025-01-10",
    identityVerification: "Cédula de ciudadanía",
    securityQuestion: "¿Cómo se llama tu madre?",
    observations: "Usuario activo desde enero",
  },
  {
    fullName: "María Fernanda",
    email: "maria.fernanda@gmail.com",
    phone: "3107654321",
    userType: "Juez",
    institution: "Juzgado Primero",
    identificationNumber: "JU9876543",
    region: "Medellín",
    address: "Carrera 45 #12-34",
    accessAreas: "Judicial",
    registrationDate: "2025-01-15",
    identityVerification: "Tarjeta profesional",
    securityQuestion: "¿Cuál es tu color favorito?",
    observations: "Tiene permisos administrativos",
  },
  {
    fullName: "Carlos Rodríguez",
    email: "carlos.rodriguez@gmail.com",
    phone: "3058765432",
    userType: "Tribunal",
    institution: "Tribunal Distrital",
    identificationNumber: "TR5432109",
    region: "Cali",
    address: "Avenida 5 Norte #10-20",
    accessAreas: "Auditoría",
    registrationDate: "2025-01-18",
    identityVerification: "Pasaporte",
    securityQuestion: "¿En qué ciudad naciste?",
    observations: "Usuario con restricciones de acceso",
  },
  {
    fullName: "Luisa Pérez",
    email: "luisa.perez@gmail.com",
    phone: "3201234987",
    userType: "Abogado",
    institution: "Corte Suprema",
    identificationNumber: "CO7854123",
    region: "Cartagena",
    address: "Calle del Arzobispado #3-15",
    accessAreas: "Legal y Consultas",
    registrationDate: "2025-01-05",
    identityVerification: "Cédula",
    securityQuestion: "¿Cómo se llamaba tu primer colegio?",
    observations: "Tiene múltiples solicitudes activas",
  },
  {
    fullName: "Andrés Mejía",
    email: "andres.mejia@gmail.com",
    phone: "3128765432",
    userType: "Juez",
    institution: "Juzgado Segundo",
    identificationNumber: "JU6543219",
    region: "Pereira",
    address: "Calle 14 #8-09",
    accessAreas: "Audiencias",
    registrationDate: "2025-01-12",
    identityVerification: "Licencia profesional",
    securityQuestion: "¿Cuál es tu película favorita?",
    observations: "Usuario de alta prioridad",
  },
  {
    fullName: "Camila Ortiz",
    email: "camila.ortiz@gmail.com",
    phone: "3056781243",
    userType: "Tribunal",
    institution: "Empresa de Tecnología XYZ",
    identificationNumber: "INST654321",
    region: "Manizales",
    address: "Carrera 21 #45-67",
    accessAreas: "Técnico",
    registrationDate: "2025-01-03",
    identityVerification: "Certificación técnica",
    securityQuestion: "¿Cuál es tu lugar favorito?",
    observations: "Certificada en sistemas de seguridad",
  },
  {
    fullName: "Ricardo López",
    email: "ricardo.lopez@gmail.com",
    phone: "3012345678",
    userType: "Abogado",
    institution: "Juzgado Civil Tercero",
    identificationNumber: "AB7890123",
    region: "Villavicencio",
    address: "Diagonal 15 #23-45",
    accessAreas: "Legal y Técnico",
    registrationDate: "2025-01-02",
    identityVerification: "Cédula de ciudadanía",
    securityQuestion: "¿Qué marca fue tu primer auto?",
    observations: "Requiere renovación anual de acceso",
  },
  {
    fullName: "Tatiana Ramírez",
    email: "tatiana.ramirez@gmail.com",
    phone: "3194567821",
    userType: "Tribunal",
    institution: "Tribunal Superior del Atlántico",
    identificationNumber: "TR147852",
    region: "Barranquilla",
    address: "Calle 50 #20-30",
    accessAreas: "Supervisión",
    registrationDate: "2025-01-08",
    identityVerification: "Tarjeta profesional",
    securityQuestion: "¿Qué sabor de helado prefieres?",
    observations: "Reportes trimestrales requeridos",
  },
  {
    fullName: "Paola Gómez",
    email: "paola.gomez@gmail.com",
    phone: "3114569870",
    userType: "Juez",
    institution: "Corte Constitucional",
    identificationNumber: "JU112233",
    region: "Bogotá",
    address: "Carrera 7 #20-15",
    accessAreas: "Judicial y Administrativo",
    registrationDate: "2025-01-22",
    identityVerification: "Cédula",
    securityQuestion: "¿Qué nombre tenía tu primera mascota?",
    observations: "Tiene acceso a casos especiales",
  },
  {
    fullName: "Martha Gómez",
    email: "martha.gomez@gmail.com",
    phone: "3114569870",
    userType: "Juez",
    institution: "Corte Constitucional",
    identificationNumber: "JU112233",
    region: "Bogotá",
    address: "Carrera 32 #9-12",
    accessAreas: "Judicial y Administrativo",
    registrationDate: "2025-01-22",
    identityVerification: "Cédula",
    securityQuestion: "¿Qué nombre tenía tu primera mascota?",
    observations: "Tiene acceso a casos especiales",
  },

  {
    fullName: "Andres Parrado",
    email: "andres.parrado@gmail.com",
    phone: "3114569870",
    userType: "Abogado",
    institution: "Corte Constitucional",
    identificationNumber: "JU112233",
    region: "Bogotá",
    address: "Carrera 7 #20-15",
    accessAreas: "Judicial y Administrativo",
    registrationDate: "2025-01-22",
    identityVerification: "Cédula",
    securityQuestion: "¿Qué nombre tenía tu primera mascota?",
    observations: "Tiene acceso a casos especiales",
  },
  {
    fullName: "Stive Leguizamon",
    email: "stiven@gmail.com",
    phone: "3114569870",
    userType: "Juez",
    institution: "Corte Constitucional",
    identificationNumber: "JU112233",
    region: "Monterry",
    address: "Carrera 8 #25-15",
    accessAreas: "Judicial y Administrativo",
    registrationDate: "2025-01-22",
    identityVerification: "Cédula",
    securityQuestion: "¿Qué nombre tenía tu primera mascota?",
    observations: "Tiene acceso a casos especiales",
  },
];

export const requests = [
  {
    requester_type: "Juez",
    requester_name: "Juan Pérez",
    identification_number: "123456789",
    situation_type: "Condena",
    request_date: "2023-10-01",
    status: "Positivo",
  },
  {
    requester_type: "Tribunal",
    requester_name: "Tech Solutions S.A.",
    identification_number: "987654321",
    situation_type: "Sujeción a control",
    request_date: "2023-10-02",
    status: "Negativo",
  },
  {
    requester_type: "Abogado",
    requester_name: "María Gómez",
    identification_number: "456789123",
    situation_type: "Condena",
    request_date: "2023-10-03",
    status: "No recomendable",
  },
  {
    requester_type: "Juez",
    requester_name: "Ayuda Humanitaria",
    identification_number: "321654987",
    situation_type: "Sujeción a control",
    request_date: "2023-10-04",
    status: "Sin respuesta",
  },
  {
    requester_type: "Tribunal",
    requester_name: "Carlos Rodríguez",
    identification_number: "789123456",
    situation_type: "Accidente de tránsito",
    request_date: "2023-10-05",
    status: "Positivo",
  },
  {
    requester_type: "Abogado",
    requester_name: "Constructora XYZ",
    identification_number: "654987321",
    situation_type: "Condena",
    request_date: "2023-10-06",
    status: "Negativo",
  },
  {
    requester_type: "Juez",
    requester_name: "Ana López",
    identification_number: "234567891",
    situation_type: "Otro",
    request_date: "2023-10-07",
    status: "No recomendable",
  },
  {
    requester_type: "Tribunal",
    requester_name: "Alimentos Saludables S.A.",
    identification_number: "876543219",
    situation_type: "Sujeción a control",
    request_date: "2023-10-08",
    status: "Sin respuesta",
  },
  {
    requester_type: "Abogado",
    requester_name: "Luis Martínez",
    identification_number: "345678912",
    situation_type: "Condena",
    request_date: "2023-10-09",
    status: "Positivo",
  },
  {
    requester_type: "Juez",
    requester_name: "Protección Animal",
    identification_number: "432198765",
    situation_type: "Sujeción a control",
    request_date: "2023-10-10",
    status: "Negativo",
  },
  {
    requester_type: "Tribunal",
    requester_name: "Sofía Ramírez",
    identification_number: "567891234",
    situation_type: "Condena",
    request_date: "2023-10-11",
    status: "No recomendable",
  },
  {
    requester_type: "Abogado",
    requester_name: "Transportes Rápidos",
    identification_number: "219876543",
    situation_type: "Otro",
    request_date: "2023-10-12",
    status: "Sin respuesta",
  },
  {
    requester_type: "Juez",
    requester_name: "Pedro Sánchez",
    identification_number: "678912345",
    situation_type: "Sujeción a control",
    request_date: "2023-10-13",
    status: "Positivo",
  },
  {
    requester_type: "Tribunal",
    requester_name: "Educación para Todos",
    identification_number: "543219876",
    situation_type: "Otro",
    request_date: "2023-10-14",
    status: "Negativo",
  },
  {
    requester_type: "Abogado",
    requester_name: "Laura Torres",
    identification_number: "789123456",
    situation_type: "Condena",
    request_date: "2023-10-15",
    status: "No recomendable",
  },
];
