export const profiles = [
  {
    id: 1,
    name: "Yosip Mike Colin",
    nit: "83749234",
    perfil: "Requiriente",
    status: "Activo",
  },
  {
    id: 2,
    name: "Andres Alfonso",
    nit: "5937450378",
    perfil: "Coordinador",
    status: "Inactivo",
  },
  {
    id: 3,
    name: "Maria Salazar",
    nit: "5905645028",
    perfil: "Administrador",
    status: "Activo",
  },
  {
    id: 4,
    name: "Luciana Gómez",
    nit: "4538294850",
    perfil: "Requiriente",
    status: "Activo",
  },
  {
    id: 5,
    name: "Carlos Pérez",
    nit: "5893247324",
    perfil: "Administrador",
    status: "Inactivo",
  },
  {
    id: 6,
    name: "Laura Martínez",
    nit: "4823952345",
    perfil: "Requiriente",
    status: "Activo",
  },
  {
    id: 7,
    name: "Jorge Fernández",
    nit: "7583940238",
    perfil: "Coordinador",
    status: "Activo",
  },
  {
    id: 8,
    name: "Andrea Torres",
    nit: "9384752384",
    perfil: "Administrador",
    status: "Activo",
  },
  {
    id: 9,
    name: "Camila Ruiz",
    nit: "8364928472",
    perfil: "Coordinador",
    status: "Inactivo",
  },
  {
    id: 10,
    name: "Felipe Mejía",
    nit: "2394853205",
    perfil: "Coordinador",
    status: "Activo",
  },
  {
    id: 11,
    name: "Paola Herrera",
    nit: "7382947583",
    perfil: "Requiriente",
    status: "Activo",
  },
  {
    id: 12,
    name: "Sebastián Vega",
    nit: "5932840239",
    perfil: "Requiriente",
    status: "Inactivo",
  },
  {
    id: 13,
    name: "Natalia Castro",
    nit: "8402938472",
    perfil: "Administrador",
    status: "Activo",
  },
  {
    id: 14,
    name: "Fernando Morales",
    nit: "7562937482",
    perfil: "Coordinador",
    status: "Inactivo",
  },
  {
    id: 15,
    name: "Sofia Rojas",
    nit: "2938745029",
    perfil: "Requiriente",
    status: "Activo",
  },
];
