export const users = [
  {
    id: 1,
    name: "Yosip Mike Colin",
    nit: "83749234",
    perfil: "Requiriente",
    status: "Activo",
    email: "yosipmikecolin@example.com",
    creation_date: "2022-03-15",
    phone: "+57 310 123 4567",
  },
  {
    id: 2,
    name: "Andres Alfonso",
    nit: "5937450378",
    perfil: "Coordinador",
    status: "Inactivo",
    email: "andresalfonso@example.com",
    creation_date: "2021-07-22",
    phone: "+57 320 234 5678",
  },
  {
    id: 3,
    name: "Maria Salazar",
    nit: "5905645028",
    perfil: "Administrador",
    status: "Activo",
    email: "mariasalazar@example.com",
    creation_date: "2023-01-10",
    phone: "+57 300 345 6789",
  },
  {
    id: 4,
    name: "Luciana Gómez",
    nit: "4538294850",
    perfil: "Requiriente",
    status: "Activo",
    email: "lucianagomez@example.com",
    creation_date: "2022-11-05",
    phone: "+57 315 456 7890",
  },
  {
    id: 5,
    name: "Carlos Pérez",
    nit: "5893247324",
    perfil: "Administrador",
    status: "Inactivo",
    email: "carlosperez@example.com",
    creation_date: "2021-09-30",
    phone: "+57 318 567 8901",
  },
  {
    id: 6,
    name: "Laura Martínez",
    nit: "4823952345",
    perfil: "Requiriente",
    status: "Activo",
    email: "lauramartinez@example.com",
    creation_date: "2023-04-12",
    phone: "+57 311 678 9012",
  },
  {
    id: 7,
    name: "Jorge Fernández",
    nit: "7583940238",
    perfil: "Coordinador",
    status: "Activo",
    email: "jorgefernandez@example.com",
    creation_date: "2022-08-19",
    phone: "+57 313 789 0123",
  },
  {
    id: 8,
    name: "Andrea Torres",
    nit: "9384752384",
    perfil: "Administrador",
    status: "Activo",
    email: "andreatorres@example.com",
    creation_date: "2021-12-25",
    phone: "+57 314 890 1234",
  },
  {
    id: 9,
    name: "Camila Ruiz",
    nit: "8364928472",
    perfil: "Coordinador",
    status: "Inactivo",
    email: "camilaruiz@example.com",
    creation_date: "2023-02-14",
    phone: "+57 317 901 2345",
  },
  {
    id: 10,
    name: "Felipe Mejía",
    nit: "2394853205",
    perfil: "Coordinador",
    status: "Activo",
    email: "felipemejia@example.com",
    creation_date: "2022-05-20",
    phone: "+57 319 012 3456",
  },
  {
    id: 11,
    name: "Paola Herrera",
    nit: "7382947583",
    perfil: "Requiriente",
    status: "Activo",
    email: "paolaherrera@example.com",
    creation_date: "2021-10-08",
    phone: "+57 312 123 4567",
  },
  {
    id: 12,
    name: "Sebastián Vega",
    nit: "5932840239",
    perfil: "Requiriente",
    status: "Inactivo",
    email: "sebastianvega@example.com",
    creation_date: "2023-03-01",
    phone: "+57 316 234 5678",
  },
  {
    id: 13,
    name: "Natalia Castro",
    nit: "8402938472",
    perfil: "Administrador",
    status: "Activo",
    email: "nataliacastro@example.com",
    creation_date: "2022-06-18",
    phone: "+57 310 345 6789",
  },
  {
    id: 14,
    name: "Fernando Morales",
    nit: "7562937482",
    perfil: "Coordinador",
    status: "Inactivo",
    email: "fernandomorales@example.com",
    creation_date: "2021-11-11",
    phone: "+57 320 456 7890",
  },
  {
    id: 15,
    name: "Sofia Rojas",
    nit: "2938745029",
    perfil: "Requiriente",
    status: "Activo",
    email: "sofiarojas@example.com",
    creation_date: "2023-05-09",
    phone: "+57 300 567 8901",
  },
];
export const carriers = [
  {
    id: 1,
    fullName: "Juan Pérez",
    socialName: "Juancho",
    nationality: "Colombia",
    countryCode: "CO",
    maritalStatus: "Soltero",
    gender: "Masculino",
    run: "12345678-9",
    phone: "+57 300 123 4567",
    typeCurrent: "Personas condenada",
    birthDate: "1985-05-15",
    penaltyType: "Prisión",
    appealsCourt: "Corte de Apelaciones de Bogotá",
    courtRegion: "Metropolitana",
    court: "Tribunal de Bogotá",
    ruc: "123456789",
    rit: "987654321",
    rol: "ROL12345",
    crs: "CRS Bogotá",
    inclusionExclusionAreas: "Área Norte, Área Sur",
    measureDuration: "5 años",
    controlSchedule: "Lunes a Viernes, 8:00 - 18:00",
    effectiveControlPeriod: "3 años",
    feasibilityRequests: "Solicitud de factibilidad técnica aprobada",
    sentence: "Sentencia condenatoria de 5 años",
    installationProgramming: "Programación completada",
    installationsPerformed: "Instalación realizada el 2023-01-15",
    modificationResolutions: "Resolución de modificación de medida",
    technicalSupports: "Soporte técnico realizado el 2023-02-01",
    nonComplianceReports: "Informe de incumplimiento del 2023-03-01",
    controlDays: "Días de control: 300, Días de incumplimiento: 5",
    uninstallations: "Desinstalación por término de medida",
  },
  {
    id: 2,
    fullName: "María García",
    socialName: "Maru",
    nationality: "México",
    countryCode: "MX",
    maritalStatus: "Casada",
    gender: "Femenino",
    run: "87654321-0",
    phone: "+52 55 9876 5432",
    typeCurrent: "Personas sujeta a control",
    birthDate: "1990-08-20",
    penaltyType: "Libertad condicional",
    appealsCourt: "Corte de Apelaciones de Ciudad de México",
    courtRegion: "Metropolitana",
    court: "Tribunal de Ciudad de México",
    ruc: "987654321",
    rit: "123456789",
    rol: "ROL54321",
    crs: "CRS Ciudad de México",
    inclusionExclusionAreas: "Área Centro, Área Oeste",
    measureDuration: "3 años",
    controlSchedule: "Lunes a Viernes, 9:00 - 17:00",
    effectiveControlPeriod: "2 años",
    feasibilityRequests: "Solicitud de factibilidad técnica en revisión",
    sentence: "Resolución judicial de libertad condicional",
    installationProgramming: "Programación pendiente",
    installationsPerformed: "Instalación pendiente",
    modificationResolutions: "Resolución de modificación de medida",
    technicalSupports: "Soporte técnico pendiente",
    nonComplianceReports: "Informe de incumplimiento del 2023-04-01",
    controlDays: "Días de control: 200, Días de incumplimiento: 10",
    uninstallations: "Desinstalación por incumplimiento",
  },
  {
    id: 3,
    fullName: "Carlos López",
    socialName: "Carlitos",
    nationality: "Chile",
    countryCode: "CL",
    maritalStatus: "Divorciado",
    gender: "Masculino",
    run: "11223344-5",
    phone: "+56 9 8765 4321",
    typeCurrent: "Víctima",
    birthDate: "1978-12-10",
    penaltyType: "Medida de protección",
    appealsCourt: "Corte de Apelaciones de Santiago",
    courtRegion: "Metropolitana",
    court: "Tribunal de Santiago",
    ruc: "112233445",
    rit: "556677889",
    rol: "ROL998877",
    crs: "CRS Santiago",
    inclusionExclusionAreas: "Área Este, Área Sur",
    measureDuration: "2 años",
    controlSchedule: "Lunes a Viernes, 10:00 - 16:00",
    effectiveControlPeriod: "1 año",
    feasibilityRequests: "Solicitud de factibilidad técnica aprobada",
    sentence: "Resolución de protección",
    installationProgramming: "Programación completada",
    installationsPerformed: "Instalación realizada el 2023-05-01",
    modificationResolutions: "Resolución de modificación de medida",
    technicalSupports: "Soporte técnico realizado el 2023-06-01",
    nonComplianceReports: "Informe de incumplimiento del 2023-07-01",
    controlDays: "Días de control: 150, Días de incumplimiento: 3",
    uninstallations: "Desinstalación por término de medida",
  },
  {
    id: 4,
    fullName: "Sofía Ramírez",
    socialName: "Sofi",
    nationality: "Argentina",
    countryCode: "AR",
    maritalStatus: "Soltera",
    gender: "Femenino",
    run: "99887766-3",
    phone: "+54 11 1234 5678",
    typeCurrent: "Personas condenada",
    birthDate: "1982-03-25",
    penaltyType: "Prisión domiciliaria",
    appealsCourt: "Corte de Apelaciones de Buenos Aires",
    courtRegion: "Metropolitana",
    court: "Tribunal de Buenos Aires",
    ruc: "998877665",
    rit: "334455667",
    rol: "ROL112233",
    crs: "CRS Buenos Aires",
    inclusionExclusionAreas: "Área Norte, Área Centro",
    measureDuration: "4 años",
    controlSchedule: "Lunes a Viernes, 7:00 - 19:00",
    effectiveControlPeriod: "2 años",
    feasibilityRequests: "Solicitud de factibilidad técnica aprobada",
    sentence: "Sentencia condenatoria de 4 años",
    installationProgramming: "Programación completada",
    installationsPerformed: "Instalación realizada el 2023-02-10",
    modificationResolutions: "Resolución de modificación de medida",
    technicalSupports: "Soporte técnico realizado el 2023-03-15",
    nonComplianceReports: "Informe de incumplimiento del 2023-04-20",
    controlDays: "Días de control: 250, Días de incumplimiento: 8",
    uninstallations: "Desinstalación por término de medida",
  },
  {
    id: 5,
    fullName: "Andrés González",
    socialName: "Andy",
    nationality: "España",
    countryCode: "ES",
    maritalStatus: "Casado",
    gender: "Masculino",
    run: "33445566-T",
    phone: "+34 600 123 456",
    typeCurrent: "Personas sujeta a control",
    birthDate: "1975-07-12",
    penaltyType: "Libertad vigilada",
    appealsCourt: "Corte de Apelaciones de Madrid",
    courtRegion: "Metropolitana",
    court: "Tribunal de Madrid",
    ruc: "334455667",
    rit: "998877665",
    rol: "ROL445566",
    crs: "CRS Madrid",
    inclusionExclusionAreas: "Área Centro, Área Oeste",
    measureDuration: "3 años",
    controlSchedule: "Lunes a Viernes, 8:00 - 18:00",
    effectiveControlPeriod: "1.5 años",
    feasibilityRequests: "Solicitud de factibilidad técnica en revisión",
    sentence: "Resolución judicial de libertad vigilada",
    installationProgramming: "Programación pendiente",
    installationsPerformed: "Instalación pendiente",
    modificationResolutions: "Resolución de modificación de medida",
    technicalSupports: "Soporte técnico pendiente",
    nonComplianceReports: "Informe de incumplimiento del 2023-05-01",
    controlDays: "Días de control: 180, Días de incumplimiento: 6",
    uninstallations: "Desinstalación por incumplimiento",
  },
  {
    id: 6,
    fullName: "Lucía Fernández",
    socialName: "Lucy",
    nationality: "Perú",
    countryCode: "PE",
    maritalStatus: "Viuda",
    gender: "Femenino",
    run: "66778899-2",
    phone: "+51 1 6543 2109",
    typeCurrent: "Víctima",
    birthDate: "1988-09-30",
    penaltyType: "Medida de protección",
    appealsCourt: "Corte de Apelaciones de Lima",
    courtRegion: "Metropolitana",
    court: "Tribunal de Lima",
    ruc: "667788992",
    rit: "112233445",
    rol: "ROL556677",
    crs: "CRS Lima",
    inclusionExclusionAreas: "Área Norte, Área Este",
    measureDuration: "2 años",
    controlSchedule: "Lunes a Viernes, 9:00 - 17:00",
    effectiveControlPeriod: "1 año",
    feasibilityRequests: "Solicitud de factibilidad técnica aprobada",
    sentence: "Resolución de protección",
    installationProgramming: "Programación completada",
    installationsPerformed: "Instalación realizada el 2023-06-15",
    modificationResolutions: "Resolución de modificación de medida",
    technicalSupports: "Soporte técnico realizado el 2023-07-01",
    nonComplianceReports: "Informe de incumplimiento del 2023-08-01",
    controlDays: "Días de control: 120, Días de incumplimiento: 2",
    uninstallations: "Desinstalación por término de medida",
  },
  {
    id: 7,
    fullName: "Miguel Torres",
    socialName: "Mike",
    nationality: "Venezuela",
    countryCode: "VE",
    maritalStatus: "Separado",
    gender: "Masculino",
    run: "11225588-6",
    phone: "+58 212 123 4567",
    typeCurrent: "Personas condenada",
    birthDate: "1980-04-18",
    penaltyType: "Prisión",
    appealsCourt: "Corte de Apelaciones de Caracas",
    courtRegion: "Metropolitana",
    court: "Tribunal de Caracas",
    ruc: "112255886",
    rit: "998877664",
    rol: "ROL778899",
    crs: "CRS Caracas",
    inclusionExclusionAreas: "Área Centro, Área Sur",
    measureDuration: "6 años",
    controlSchedule: "Lunes a Viernes, 8:00 - 20:00",
    effectiveControlPeriod: "4 años",
    feasibilityRequests: "Solicitud de factibilidad técnica aprobada",
    sentence: "Sentencia condenatoria de 6 años",
    installationProgramming: "Programación completada",
    installationsPerformed: "Instalación realizada el 2023-03-10",
    modificationResolutions: "Resolución de modificación de medida",
    technicalSupports: "Soporte técnico realizado el 2023-04-15",
    nonComplianceReports: "Informe de incumplimiento del 2023-05-20",
    controlDays: "Días de control: 400, Días de incumplimiento: 12",
    uninstallations: "Desinstalación por término de medida",
  },
  {
    id: 8,
    fullName: "Ana Martínez",
    socialName: "Anita",
    nationality: "Uruguay",
    countryCode: "UY",
    maritalStatus: "Soltera",
    gender: "Femenino",
    run: "55443322-1",
    phone: "+598 99 987 654",
    typeCurrent: "Personas sujeta a control",
    birthDate: "1992-11-05",
    penaltyType: "Libertad condicional",
    appealsCourt: "Corte de Apelaciones de Montevideo",
    courtRegion: "Metropolitana",
    court: "Tribunal de Montevideo",
    ruc: "554433221",
    rit: "112233445",
    rol: "ROL334455",
    crs: "CRS Montevideo",
    inclusionExclusionAreas: "Área Oeste, Área Este",
    measureDuration: "3 años",
    controlSchedule: "Lunes a Viernes, 9:00 - 18:00",
    effectiveControlPeriod: "2 años",
    feasibilityRequests: "Solicitud de factibilidad técnica en revisión",
    sentence: "Resolución judicial de libertad condicional",
    installationProgramming: "Programación pendiente",
    installationsPerformed: "Instalación pendiente",
    modificationResolutions: "Resolución de modificación de medida",
    technicalSupports: "Soporte técnico pendiente",
    nonComplianceReports: "Informe de incumplimiento del 2023-06-01",
    controlDays: "Días de control: 220, Días de incumplimiento: 7",
    uninstallations: "Desinstalación por incumplimiento",
  },
  {
    id: 9,
    fullName: "José Díaz",
    socialName: "Pepe",
    nationality: "Paraguay",
    countryCode: "PY",
    maritalStatus: "Soltero",
    gender: "Masculino",
    run: "22334455-7",
    phone: "+595 21 123 456",
    typeCurrent: "Víctima",
    birthDate: "1987-02-14",
    penaltyType: "Medida de protección",
    appealsCourt: "Corte de Apelaciones de Asunción",
    courtRegion: "Metropolitana",
    court: "Tribunal de Asunción",
    ruc: "223344557",
    rit: "667788993",
    rol: "ROL112244",
    crs: "CRS Asunción",
    inclusionExclusionAreas: "Área Norte, Área Sur",
    measureDuration: "2 años",
    controlSchedule: "Lunes a Viernes, 10:00 - 16:00",
    effectiveControlPeriod: "1 año",
    feasibilityRequests: "Solicitud de factibilidad técnica aprobada",
    sentence: "Resolución de protección",
    installationProgramming: "Programación completada",
    installationsPerformed: "Instalación realizada el 2023-07-01",
    modificationResolutions: "Resolución de modificación de medida",
    technicalSupports: "Soporte técnico realizado el 2023-08-01",
    nonComplianceReports: "Informe de incumplimiento del 2023-09-01",
    controlDays: "Días de control: 150, Días de incumplimiento: 4",
    uninstallations: "Desinstalación por término de medida",
  },
  {
    id: 10,
    fullName: "Paula Rodríguez",
    socialName: "Pau",
    nationality: "Bolivia",
    countryCode: "BO",
    maritalStatus: "Casada",
    gender: "Femenino",
    run: "77889966-4",
    phone: "+591 3 456 789",
    typeCurrent: "Personas condenada",
    birthDate: "1983-06-22",
    penaltyType: "Prisión domiciliaria",
    appealsCourt: "Corte de Apelaciones de La Paz",
    courtRegion: "Metropolitana",
    court: "Tribunal de La Paz",
    ruc: "778899664",
    rit: "334455667",
    rol: "ROL998877",
    crs: "CRS La Paz",
    inclusionExclusionAreas: "Área Centro, Área Oeste",
    measureDuration: "4 años",
    controlSchedule: "Lunes a Viernes, 7:00 - 19:00",
    effectiveControlPeriod: "2 años",
    feasibilityRequests: "Solicitud de factibilidad técnica aprobada",
    sentence: "Sentencia condenatoria de 4 años",
    installationProgramming: "Programación completada",
    installationsPerformed: "Instalación realizada el 2023-04-10",
    modificationResolutions: "Resolución de modificación de medida",
    technicalSupports: "Soporte técnico realizado el 2023-05-15",
    nonComplianceReports: "Informe de incumplimiento del 2023-06-20",
    controlDays: "Días de control: 300, Días de incumplimiento: 10",
    uninstallations: "Desinstalación por término de medida",
  },
  {
    id: 11,
    fullName: "Alberto Vargas",
    socialName: "Beto",
    nationality: "Ecuador",
    countryCode: "EC",
    maritalStatus: "Divorciado",
    gender: "Masculino",
    run: "55667788-9",
    phone: "+593 4 678 901",
    typeCurrent: "Personas sujeta a control",
    birthDate: "1979-09-12",
    penaltyType: "Libertad vigilada",
    appealsCourt: "Corte de Apelaciones de Quito",
    courtRegion: "Metropolitana",
    court: "Tribunal de Quito",
    ruc: "556677889",
    rit: "112233445",
    rol: "ROL334455",
    crs: "CRS Quito",
    inclusionExclusionAreas: "Área Norte, Área Este",
    measureDuration: "3 años",
    controlSchedule: "Lunes a Viernes, 8:00 - 18:00",
    effectiveControlPeriod: "1.5 años",
    feasibilityRequests: "Solicitud de factibilidad técnica en revisión",
    sentence: "Resolución judicial de libertad vigilada",
    installationProgramming: "Programación pendiente",
    installationsPerformed: "Instalación pendiente",
    modificationResolutions: "Resolución de modificación de medida",
    technicalSupports: "Soporte técnico pendiente",
    nonComplianceReports: "Informe de incumplimiento del 2023-07-01",
    controlDays: "Días de control: 200, Días de incumplimiento: 8",
    uninstallations: "Desinstalación por incumplimiento",
  },
  {
    id: 12,
    fullName: "Carolina Méndez",
    socialName: "Caro",
    nationality: "Brasil",
    countryCode: "BR",
    maritalStatus: "Soltera",
    gender: "Femenino",
    run: "33221144-8",
    phone: "+55 11 98765-4321",
    typeCurrent: "Víctima",
    birthDate: "1995-03-08",
    penaltyType: "Medida de protección",
    appealsCourt: "Corte de Apelaciones de São Paulo",
    courtRegion: "Metropolitana",
    court: "Tribunal de São Paulo",
    ruc: "332211448",
    rit: "998877665",
    rol: "ROL556677",
    crs: "CRS São Paulo",
    inclusionExclusionAreas: "Área Centro, Área Sur",
    measureDuration: "2 años",
    controlSchedule: "Lunes a Viernes, 9:00 - 17:00",
    effectiveControlPeriod: "1 año",
    feasibilityRequests: "Solicitud de factibilidad técnica aprobada",
    sentence: "Resolución de protección",
    installationProgramming: "Programación completada",
    installationsPerformed: "Instalación realizada el 2023-08-01",
    modificationResolutions: "Resolución de modificación de medida",
    technicalSupports: "Soporte técnico realizado el 2023-09-01",
    nonComplianceReports: "Informe de incumplimiento del 2023-10-01",
    controlDays: "Días de control: 180, Días de incumplimiento: 5",
    uninstallations: "Desinstalación por término de medida",
  },
  {
    id: 13,
    fullName: "Diego Jiménez",
    socialName: "Jimmy",
    nationality: "Panamá",
    countryCode: "PA",
    maritalStatus: "Soltero",
    gender: "Masculino",
    run: "66778899-0",
    phone: "+507 678 9012",
    typeCurrent: "Personas condenada",
    birthDate: "1984-07-19",
    penaltyType: "Prisión",
    appealsCourt: "Corte de Apelaciones de Panamá",
    courtRegion: "Metropolitana",
    court: "Tribunal de Panamá",
    ruc: "667788990",
    rit: "112233445",
    rol: "ROL998877",
    crs: "CRS Panamá",
    inclusionExclusionAreas: "Área Norte, Área Este",
    measureDuration: "5 años",
    controlSchedule: "Lunes a Viernes, 8:00 - 18:00",
    effectiveControlPeriod: "3 años",
    feasibilityRequests: "Solicitud de factibilidad técnica aprobada",
    sentence: "Sentencia condenatoria de 5 años",
    installationProgramming: "Programación completada",
    installationsPerformed: "Instalación realizada el 2023-05-10",
    modificationResolutions: "Resolución de modificación de medida",
    technicalSupports: "Soporte técnico realizado el 2023-06-15",
    nonComplianceReports: "Informe de incumplimiento del 2023-07-20",
    controlDays: "Días de control: 350, Días de incumplimiento: 9",
    uninstallations: "Desinstalación por término de medida",
  },
  {
    id: 14,
    fullName: "Gabriela Morales",
    socialName: "Gaby",
    nationality: "Puerto Rico",
    countryCode: "PR",
    maritalStatus: "Viuda",
    gender: "Femenino",
    run: "44556677-1",
    phone: "+1 787 654 3210",
    typeCurrent: "Personas sujeta a control",
    birthDate: "1976-12-03",
    penaltyType: "Libertad condicional",
    appealsCourt: "Corte de Apelaciones de San Juan",
    courtRegion: "Metropolitana",
    court: "Tribunal de San Juan",
    ruc: "445566771",
    rit: "998877664",
    rol: "ROL112233",
    crs: "CRS San Juan",
    inclusionExclusionAreas: "Área Oeste, Área Sur",
    measureDuration: "3 años",
    controlSchedule: "Lunes a Viernes, 9:00 - 17:00",
    effectiveControlPeriod: "2 años",
    feasibilityRequests: "Solicitud de factibilidad técnica en revisión",
    sentence: "Resolución judicial de libertad condicional",
    installationProgramming: "Programación pendiente",
    installationsPerformed: "Instalación pendiente",
    modificationResolutions: "Resolución de modificación de medida",
    technicalSupports: "Soporte técnico pendiente",
    nonComplianceReports: "Informe de incumplimiento del 2023-08-01",
    controlDays: "Días de control: 240, Días de incumplimiento: 6",
    uninstallations: "Desinstalación por incumplimiento",
  },
  {
    id: 15,
    fullName: "Ricardo Peña",
    socialName: "Richie",
    nationality: "Honduras",
    countryCode: "HN",
    maritalStatus: "Casado",
    gender: "Masculino",
    run: "11447788-5",
    phone: "+504 2234 5678",
    typeCurrent: "Víctima",
    birthDate: "1989-10-25",
    penaltyType: "Medida de protección",
    appealsCourt: "Corte de Apelaciones de Tegucigalpa",
    courtRegion: "Metropolitana",
    court: "Tribunal de Tegucigalpa",
    ruc: "114477885",
    rit: "556677889",
    rol: "ROL334455",
    crs: "CRS Tegucigalpa",
    inclusionExclusionAreas: "Área Centro, Área Este",
    measureDuration: "2 años",
    controlSchedule: "Lunes a Viernes, 10:00 - 16:00",
    effectiveControlPeriod: "1 año",
    feasibilityRequests: "Solicitud de factibilidad técnica aprobada",
    sentence: "Resolución de protección",
    installationProgramming: "Programación completada",
    installationsPerformed: "Instalación realizada el 2023-09-01",
    modificationResolutions: "Resolución de modificación de medida",
    technicalSupports: "Soporte técnico realizado el 2023-10-01",
    nonComplianceReports: "Informe de incumplimiento del 2023-11-01",
    controlDays: "Días de control: 160, Días de incumplimiento: 3",
    uninstallations: "Desinstalación por término de medida",
  },
];

export const requesters = [
  {
    fullName: "José Alfredo",
    email: "jose.alfredo@gmail.com",
    phone: "3001234567",
    userType: "Abogado",
    institution: "Tribunal Superior",
    identificationNumber: "AB1234567",
    region: "Bogotá",
    address: "Calle 123 #45-67",
    accessAreas: "Legal",
    registrationDate: "2025-01-10",
    identityVerification: "Cédula de ciudadanía",
    securityQuestion: "¿Cómo se llama tu madre?",
    observations: "Usuario activo desde enero",
  },
  {
    fullName: "María Fernanda",
    email: "maria.fernanda@gmail.com",
    phone: "3107654321",
    userType: "Juez",
    institution: "Juzgado Primero",
    identificationNumber: "JU9876543",
    region: "Medellín",
    address: "Carrera 45 #12-34",
    accessAreas: "Judicial",
    registrationDate: "2025-01-15",
    identityVerification: "Tarjeta profesional",
    securityQuestion: "¿Cuál es tu color favorito?",
    observations: "Tiene permisos administrativos",
  },
  {
    fullName: "Carlos Rodríguez",
    email: "carlos.rodriguez@gmail.com",
    phone: "3058765432",
    userType: "Tribunal",
    institution: "Tribunal Distrital",
    identificationNumber: "TR5432109",
    region: "Cali",
    address: "Avenida 5 Norte #10-20",
    accessAreas: "Auditoría",
    registrationDate: "2025-01-18",
    identityVerification: "Pasaporte",
    securityQuestion: "¿En qué ciudad naciste?",
    observations: "Usuario con restricciones de acceso",
  },
  {
    fullName: "Luisa Pérez",
    email: "luisa.perez@gmail.com",
    phone: "3201234987",
    userType: "Abogado",
    institution: "Corte Suprema",
    identificationNumber: "CO7854123",
    region: "Cartagena",
    address: "Calle del Arzobispado #3-15",
    accessAreas: "Legal y Consultas",
    registrationDate: "2025-01-05",
    identityVerification: "Cédula",
    securityQuestion: "¿Cómo se llamaba tu primer colegio?",
    observations: "Tiene múltiples solicitudes activas",
  },
  {
    fullName: "Andrés Mejía",
    email: "andres.mejia@gmail.com",
    phone: "3128765432",
    userType: "Juez",
    institution: "Juzgado Segundo",
    identificationNumber: "JU6543219",
    region: "Pereira",
    address: "Calle 14 #8-09",
    accessAreas: "Audiencias",
    registrationDate: "2025-01-12",
    identityVerification: "Licencia profesional",
    securityQuestion: "¿Cuál es tu película favorita?",
    observations: "Usuario de alta prioridad",
  },
  {
    fullName: "Camila Ortiz",
    email: "camila.ortiz@gmail.com",
    phone: "3056781243",
    userType: "Tribunal",
    institution: "Empresa de Tecnología XYZ",
    identificationNumber: "INST654321",
    region: "Manizales",
    address: "Carrera 21 #45-67",
    accessAreas: "Técnico",
    registrationDate: "2025-01-03",
    identityVerification: "Certificación técnica",
    securityQuestion: "¿Cuál es tu lugar favorito?",
    observations: "Certificada en sistemas de seguridad",
  },
  {
    fullName: "Ricardo López",
    email: "ricardo.lopez@gmail.com",
    phone: "3012345678",
    userType: "Abogado",
    institution: "Juzgado Civil Tercero",
    identificationNumber: "AB7890123",
    region: "Villavicencio",
    address: "Diagonal 15 #23-45",
    accessAreas: "Legal y Técnico",
    registrationDate: "2025-01-02",
    identityVerification: "Cédula de ciudadanía",
    securityQuestion: "¿Qué marca fue tu primer auto?",
    observations: "Requiere renovación anual de acceso",
  },
  {
    fullName: "Tatiana Ramírez",
    email: "tatiana.ramirez@gmail.com",
    phone: "3194567821",
    userType: "Tribunal",
    institution: "Tribunal Superior del Atlántico",
    identificationNumber: "TR147852",
    region: "Barranquilla",
    address: "Calle 50 #20-30",
    accessAreas: "Supervisión",
    registrationDate: "2025-01-08",
    identityVerification: "Tarjeta profesional",
    securityQuestion: "¿Qué sabor de helado prefieres?",
    observations: "Reportes trimestrales requeridos",
  },
  {
    fullName: "Paola Gómez",
    email: "paola.gomez@gmail.com",
    phone: "3114569870",
    userType: "Juez",
    institution: "Corte Constitucional",
    identificationNumber: "JU112233",
    region: "Bogotá",
    address: "Carrera 7 #20-15",
    accessAreas: "Judicial y Administrativo",
    registrationDate: "2025-01-22",
    identityVerification: "Cédula",
    securityQuestion: "¿Qué nombre tenía tu primera mascota?",
    observations: "Tiene acceso a casos especiales",
  },
  {
    fullName: "Martha Gómez",
    email: "martha.gomez@gmail.com",
    phone: "3114569870",
    userType: "Juez",
    institution: "Corte Constitucional",
    identificationNumber: "JU112233",
    region: "Bogotá",
    address: "Carrera 32 #9-12",
    accessAreas: "Judicial y Administrativo",
    registrationDate: "2025-01-22",
    identityVerification: "Cédula",
    securityQuestion: "¿Qué nombre tenía tu primera mascota?",
    observations: "Tiene acceso a casos especiales",
  },

  {
    fullName: "Andres Parrado",
    email: "andres.parrado@gmail.com",
    phone: "3114569870",
    userType: "Abogado",
    institution: "Corte Constitucional",
    identificationNumber: "JU112233",
    region: "Bogotá",
    address: "Carrera 7 #20-15",
    accessAreas: "Judicial y Administrativo",
    registrationDate: "2025-01-22",
    identityVerification: "Cédula",
    securityQuestion: "¿Qué nombre tenía tu primera mascota?",
    observations: "Tiene acceso a casos especiales",
  },
  {
    fullName: "Stive Leguizamon",
    email: "stiven@gmail.com",
    phone: "3114569870",
    userType: "Juez",
    institution: "Corte Constitucional",
    identificationNumber: "JU112233",
    region: "Monterry",
    address: "Carrera 8 #25-15",
    accessAreas: "Judicial y Administrativo",
    registrationDate: "2025-01-22",
    identityVerification: "Cédula",
    securityQuestion: "¿Qué nombre tenía tu primera mascota?",
    observations: "Tiene acceso a casos especiales",
  },
];

export const requests = [
  {
    requester_type: "Juez",
    requester_name: "Juan Pérez",
    identification_number: "123456789",
    situation_type: "Condena",
    request_date: "2023-10-01",
    response_date: "----",
    status: "Sin respuesta",
    confirmation: "false",
    hour: "5 horas y 20 minutos",
  },
  {
    requester_type: "Tribunal",
    requester_name: "Tech Solutions S.A.",
    identification_number: "987654321",
    situation_type: "Sujeción a control",
    request_date: "2023-10-02",
    response_date: "----",
    status: "Negativo",
    confirmation: "return",
    hour: "6 horas y 12 minutos",
  },
  {
    requester_type: "Abogado",
    requester_name: "María Gómez",
    identification_number: "456789123",
    situation_type: "Condena",
    request_date: "2023-10-03",
    response_date: "2023-10-04",
    status: "No recomendable",
    confirmation: "true",
    hour: "8 horas y 30 minutos",
  },
  {
    requester_type: "Juez",
    requester_name: "Ayuda Humanitaria",
    identification_number: "321654987",
    situation_type: "Sujeción a control",
    request_date: "2023-10-04",
    response_date: "----",
    status: "Sin respuesta",
    confirmation: "false",
    hour: "9 horas y 30 minutos",
  },
  {
    requester_type: "Tribunal",
    requester_name: "Carlos Rodríguez",
    identification_number: "789123456",
    situation_type: "Accidente de tránsito",
    request_date: "2023-10-05",
    response_date: "----",
    status: "Positivo",
    confirmation: "return",
    hour: "10 horas",
  },
  {
    requester_type: "Abogado",
    requester_name: "Constructora XYZ",
    identification_number: "654987321",
    situation_type: "Condena",
    request_date: "2023-10-06",
    response_date: "2023-10-07",
    status: "Negativo",
    confirmation: "false",
    hour: "4 horas",
  },
  {
    requester_type: "Juez",
    requester_name: "Ana López",
    identification_number: "234567891",
    situation_type: "Otro",
    request_date: "2023-10-07",
    response_date: "2023-10-08",
    status: "No recomendable",
    confirmation: "true",
    hour: "5 horas",
  },
  {
    requester_type: "Tribunal",
    requester_name: "Alimentos Saludables S.A.",
    identification_number: "876543219",
    situation_type: "Sujeción a control",
    request_date: "2023-10-08",
    response_date: "----",
    status: "Sin respuesta",
    confirmation: "false",
    hour: "5 horas",
  },
  {
    requester_type: "Abogado",
    requester_name: "Luis Martínez",
    identification_number: "345678912",
    situation_type: "Condena",
    request_date: "2023-10-09",
    response_date: "2023-10-10",
    status: "Positivo",
    confirmation: "true",
    hour: "6 horas y 10 minutos",
  },
  {
    requester_type: "Juez",
    requester_name: "Protección Animal",
    identification_number: "432198765",
    situation_type: "Sujeción a control",
    request_date: "2023-10-10",
    response_date: "2023-10-11",
    status: "Negativo",
    confirmation: "false",
    hour: "3 horas",
  },
  {
    requester_type: "Tribunal",
    requester_name: "Sofía Ramírez",
    identification_number: "567891234",
    situation_type: "Condena",
    request_date: "2023-10-11",
    response_date: "2023-10-12",
    status: "No recomendable",
    confirmation: "false",
    hour: "7 horas 10 minutos",
  },
  {
    requester_type: "Abogado",
    requester_name: "Transportes Rápidos",
    identification_number: "219876543",
    situation_type: "Otro",
    request_date: "2023-10-12",
    response_date: "----",
    status: "Sin respuesta",
    confirmation: "false",
    hour: "9 horas 25 minutos",
  },
  {
    requester_type: "Juez",
    requester_name: "Pedro Sánchez",
    identification_number: "678912345",
    situation_type: "Sujeción a control",
    request_date: "2023-10-13",
    response_date: "2023-10-14",
    status: "Positivo",
    confirmation: "true",
    hour: "10 horas",
  },
  {
    requester_type: "Tribunal",
    requester_name: "Educación para Todos",
    identification_number: "543219876",
    situation_type: "Otro",
    request_date: "2023-10-14",
    response_date: "2023-10-15",
    status: "Negativo",
    confirmation: "true",
    hour: "11 horas",
  },
  {
    requester_type: "Abogado",
    requester_name: "Laura Torres",
    identification_number: "789123456",
    situation_type: "Condena",
    request_date: "2023-10-15",
    response_date: "----",
    status: "No recomendable",
    confirmation: "return",
    hour: "4 horas",
  },
];

export const workLoad = [
  { id: 1, name: "Ana García", openCases: 5, closedCases: 15, laborLoad: 75 },
  {
    id: 2,
    name: "Luis Martínez",
    openCases: 3,
    closedCases: 10,
    laborLoad: 60,
  },
  { id: 3, name: "María López", openCases: 7, closedCases: 20, laborLoad: 85 },
  {
    id: 4,
    name: "Carlos Sánchez",
    openCases: 2,
    closedCases: 8,
    laborLoad: 50,
  },
  {
    id: 5,
    name: "Sofía Ramírez",
    openCases: 6,
    closedCases: 18,
    laborLoad: 80,
  },
  {
    id: 6,
    name: "Jorge Fernández",
    openCases: 4,
    closedCases: 12,
    laborLoad: 70,
  },
  { id: 7, name: "Elena Torres", openCases: 1, closedCases: 5, laborLoad: 40 },
  { id: 8, name: "Miguel Díaz", openCases: 8, closedCases: 22, laborLoad: 90 },
  { id: 9, name: "Lucía Morales", openCases: 3, closedCases: 9, laborLoad: 55 },
  {
    id: 10,
    name: "Pedro Ortega",
    openCases: 6,
    closedCases: 16,
    laborLoad: 78,
  },
  { id: 11, name: "Carmen Ruiz", openCases: 2, closedCases: 7, laborLoad: 45 },
  {
    id: 12,
    name: "Diego Castro",
    openCases: 5,
    closedCases: 14,
    laborLoad: 72,
  },
  {
    id: 13,
    name: "Paula Jiménez",
    openCases: 4,
    closedCases: 11,
    laborLoad: 65,
  },
  {
    id: 14,
    name: "Javier Navarro",
    openCases: 9,
    closedCases: 25,
    laborLoad: 95,
  },
  { id: 15, name: "Isabel Vega", openCases: 3, closedCases: 10, laborLoad: 58 },
];
