export interface Wearer {
  id: string;
  customer_id: string;
  group_id: string;
  group_name: string;
  first_name: string;
  surname: string;
  wearer_type_id: string;
  wearer_type_name: string;
  wearer_type_colour: string;
  name: string;
  dob: string | null;
  ref: string;
  criminal_records_no: string | null;
  email: string;
  phone_type: string;
  mobile: string;
  date_added: string;
  start_tagging_time: string;
  end_tagging_time: string;
  notes: string | null;
  device_profile_id: string;
  device_profile_sb_id: string | null;
  timezone_id: string;
  ethnicity_id: string;
  gender_id: number;
  language_id: number;
  risk_level_id: string | null;
  has_photo: number;
  interpretor_required: number;
  risk_assessment: string | null;
  medical_conditions: string | null;
  monitored: string;
  timezone: string;
  gender: string;
  vibrate_tag: number;
  audible_vibrate: string | null;
  exclude_from_proximity: string;
  exclude_from_loitering: string;
  exclude_from_auto_day_report: string;
  enable_checkin: string;
  enable_checkin_locations: string;
  rf_only_profile: string;
  identifying_marks: string | null;
  number_addresses: string;
  employer_name: string | null;
  employer_position: string | null;
  employer_date_started: string | null;
  employer_additional: string | null;
  employer_address_line_1: string | null;
  employer_address_line_2: string | null;
  employer_address_city: string | null;
  employer_address_county: string | null;
  employer_address_postcode: string | null;
  employer_telephone: string | null;
  responsible_officer_id: string;
  responsible_officer: string;
  responsible_officer_phone: string | null;
  device_profile_name: string;
  stationary_download: string;
  moving_download: string;
  device_profile_sb_name: string | null;
  vv_id: string | null;
  vv_number: string | null;
  vv_enrolled: string | null;
  biometrics_enrolled: string | null;
  biometrics_enabled: string | null;
  hair_colour_id: string | null;
  eye_colour_id: string | null;
  height: string | null;
  weight: string | null;
  country_id: string;
  ethnicity: string;
  language: string;
  wearer_now: string;
  primary_address_id: string;
  primary_address_phone: string;
  primary_address_city: string;
  primary_address_name: string;
  primary_address_line1: string;
  primary_address_postcode: string;
  is_victim: string;
  enable_victim: string;
  class: string;
  sonic_class: string;
  primary_address_short: string;
  devices: any[]; // puedes tipar mejor si sabes la estructura de los devices
  nmr_open_visits: number;
  nmr_victim_associations: number;
  victim_associations: any[]; // igual aquí
}
